spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql=true:
    show-sql: true
  sql:
    init:
      mode: always